#!/bin/bash
gcloud beta compute instances create gpu-instance-1 \
    --machine-type n1-highmem-16 --zone us-east1-d \
    --accelerator type=nvidia-tesla-k80,count=2 \
    --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud \
    --maintenance-policy TERMINATE \
    --boot-disk-size 50GB \
    --metadata startup-script='#!/bin/bash
    echo "Checking for CUDA and installing."
    if ! dpkg-query -W cuda; then
      curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      dpkg -i ./cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      apt-get update
      apt-get install cuda -y
    fi
    apt-get install -y python-pip python-dev
    pip install tensorflow-gpu keras h5py

    cd ~

    apt-get install -y unzip
    wget https://storage.googleapis.com/pub/gsutil.zip
    unzip gsutil.zip

    mkdir -p /tmp/configuration-side-projects
    gsutil/gsutil cp -r gs://marcrasi-configuration/side-projects/* /tmp/configuration-side-projects/

    mkdir -p ~/.ssh
    mv /tmp/configuration-side-projects/ssh/* ~/.ssh
    chmod 600 ~/.ssh/*

    apt-get install git -y
    git clone git@github.com:marcrasi/side-projects.git
    '
